### ISSUE TITLE
翻訳エラー: [AT / A4T] タイトルの翻訳がおかしい

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/target-learn.ja-JP#1]
Issue in ./help/integrations/set-up-a4t-reports-in-analysis-workspace-for-auto-allocate-activities.md

[現在の翻訳] での A4T レポートの設定 Analysis Workspace 対象 Auto-Allocate アクティビティ
[正しい翻訳] 自動配分アクティビティ用のワーク スペースに A4T レポートを設定する
[原文] Setting up A4T reports in Analysis Workspace for Auto-Allocate activities

**Comment by mak-adobe** [comment]
@khagiwar ありがとうございます。調査を開始しました。少しお待ちください。

**Comment by mak-adobe** [comment]
@khagiwar G11N-12927 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@khagiwar 修正が完了しました。ご提案いただいた翻訳文を通常のスタイルと表記に合わせて調整させていただきました。
